### ISSUE TITLE
Error in net_establishConnection

### ISSUE THREAD

**Issue by Moe580** [Modi1987/IIWAContorlToolbox#1]
Hello,

Thank you very much for your toolbox. 
I was going through your tutorials and got a problem about starting a connection with the server.

I am finished with copying KST server files to Sunrise.workbench and sending them to the teach pendant, and am able to run "ICTServer" application in the teach pendant.
However, when I run the tutorial program of your toolbox in MATLAB during the 60 seconds of application running, the error saying this appears: **"ICT/net_establishConnection (line 491) Connection could not be established, script aborted".**

I would appreciate your help very much if you could help me.

**Comment by Modi1987** [comment]
Hi,

To solve the problem verify the following:
1- Make sure that you have the instrumentation toolbox installed in Matlab.
2- Make sure that the network (hardware) is working well, you can ping the robot IP from the terminal to verify.
3- Make sure that you are using the correct IP of the robot (note: in the provided examples the default '172.31.1.147' is used, this might differ for your robot).
4- If all the previous is ok, then it could be the firewall not allowing the communication, in this case you have to turn it off.

Cheers!

**Comment by Moe580** [comment]
Thank you very much for the reply.

1. By saying "the instrumentation toolbox", do you mean the files of [your toolbox](https://github.com/Modi1987/IIWAContorlToolbox)? If it is, I have installed all of the files.
2. Yes, I did ping the robot IP and it did not work.
3. Yes, the IP was the same as the default.
4. The firewall was on, so I turned it off. However, it still did not work.

I tried all of the four but I still have the same errors.
I am sorry for taking your time,  but I would appreciate if you could help.

**Comment by Moe580** [comment]
I realized that  "the instrumentation toolbox" might mean "Instrument Control Toolbox" of KUKA, so I installed it and tried your toolbox.
Then, I got the message below, but the tutorial program did not work.

![thumbnail_Image](https://user-images.githubusercontent.com/68943716/96418278-7c1c7480-122d-11eb-9daf-24b5291d67c8.jpg)

I think the message means that I succeeded in getting the data, but I cannot find out why the program did not work.
I would appreciate very much if you could help.

**Comment by Modi1987** [comment]
Hi,

From the figure you attached (of the smartPad), I see that the toolbox is working. However, if you look at the top of the figure you see that the Current State is "**Motion Paused**" I suppose that you did not put the robot in the Automatic Mode.
Check [this video](https://www.youtube.com/watch?v=_yTK0Gi0p3g&list=PLz558OYgHuZd-Gc2-OryITKEXefAmrvae&index=1&t=38s) at 00:39 seconds, it shows you how to put the robot in the Automatic Mode.
If this does not work, tell me which tutorial script are you using?

Cheers

**Comment by Moe580** [comment]
Hello, 

Thank you for the reply.

I put the robot in the Automatic Mode, and it worked!
I appreciate very much for your kind help all the time.

Best Regards
